source 'http://rubygems.org'
gem 'discordrb', :git => 'https://github.com/meew0/discordrb', :branch => 'master'
gem 'rumoji'
gem 'rainbow'
gem 'rake'
gem 'nokogiri'
gem 'bindata'
gem 'pry'
gem 'rubocop'