name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [11]
      fail-fast: true

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package

      - uses: actions/upload-artifact@master
        with:
          name: RC24-Bot
          path: target/RC24-Bot.jar